2024-07-21 10:51:05,627 - INFO - Starting scheduler
2024-07-21 10:51:05,627 - INFO - Updater date and time: 2024-07-21 10:51:05.627535
2024-07-21 10:51:05,629 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-21 10:51:05,629 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-21 10:51:05,629 - INFO - Scheduler started
2024-07-21 10:51:05,630 - INFO - Current time of the scheduler: 2024-07-21 10:51:05.630979
2024-07-21 10:51:05,630 - INFO - Ending scheduler
2024-07-21 10:51:08,055 - INFO - Starting scheduler
2024-07-21 10:51:08,056 - INFO - Updater date and time: 2024-07-21 10:51:08.056755
2024-07-21 10:51:08,058 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-21 10:51:08,058 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-21 10:51:08,058 - INFO - Scheduler started
2024-07-21 10:51:08,058 - INFO - Current time of the scheduler: 2024-07-21 10:51:08.058917
2024-07-21 10:51:08,058 - INFO - Ending scheduler
2024-07-21 10:51:08,082 - INFO - Watching for file changes with StatReloader
2024-07-21 11:14:40,859 - INFO - Starting scheduler
2024-07-21 11:14:40,860 - INFO - Updater date and time: 2024-07-21 11:14:40.860506
2024-07-21 11:14:40,861 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-21 11:14:40,861 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-21 11:14:40,861 - INFO - Scheduler started
2024-07-21 11:14:40,862 - INFO - Current time of the scheduler: 2024-07-21 11:14:40.862506
2024-07-21 11:14:40,862 - INFO - Ending scheduler
2024-07-21 11:14:43,239 - INFO - Starting scheduler
2024-07-21 11:14:43,239 - INFO - Updater date and time: 2024-07-21 11:14:43.239963
2024-07-21 11:14:43,240 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-21 11:14:43,240 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-21 11:14:43,240 - INFO - Scheduler started
2024-07-21 11:14:43,241 - INFO - Current time of the scheduler: 2024-07-21 11:14:43.241975
2024-07-21 11:14:43,241 - INFO - Ending scheduler
2024-07-21 11:14:43,262 - INFO - Watching for file changes with StatReloader
2024-07-21 11:15:23,014 - INFO - Starting scheduler
2024-07-21 11:15:23,016 - INFO - Updater date and time: 2024-07-21 11:15:23.016061
2024-07-21 11:15:23,017 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-21 11:15:23,017 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-21 11:15:23,017 - INFO - Scheduler started
2024-07-21 11:15:23,018 - INFO - Current time of the scheduler: 2024-07-21 11:15:23.018118
2024-07-21 11:15:23,018 - INFO - Ending scheduler
2024-07-21 11:15:25,344 - INFO - Starting scheduler
2024-07-21 11:15:25,345 - INFO - Updater date and time: 2024-07-21 11:15:25.345463
2024-07-21 11:15:25,346 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-21 11:15:25,347 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-21 11:15:25,347 - INFO - Scheduler started
2024-07-21 11:15:25,347 - INFO - Current time of the scheduler: 2024-07-21 11:15:25.347470
2024-07-21 11:15:25,347 - INFO - Ending scheduler
2024-07-21 11:15:25,369 - INFO - Watching for file changes with StatReloader
2024-07-21 11:16:00,013 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-21 11:16:00 BST)" (scheduled at 2024-07-21 11:16:00+01:00)
2024-07-21 11:16:00,013 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-21 11:21:00 BST)" (scheduled at 2024-07-21 11:16:00+01:00)
2024-07-21 11:16:00,013 - INFO - Inside the procedure sequence
2024-07-21 11:16:00,013 - INFO - Inside the procedure sequence
2024-07-21 11:16:00,193 - INFO - The input start time: 2024-07-21 10:00:00
2024-07-21 11:16:00,193 - INFO - The input start time: 2024-07-21 10:00:00
2024-07-21 11:16:21,662 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-21 11:21:00 BST)" executed successfully
2024-07-21 11:16:27,376 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-21 11:21:00 BST)" executed successfully
2024-07-21 11:21:26,597 - INFO - Starting scheduler
2024-07-21 11:21:26,598 - INFO - Updater date and time: 2024-07-21 11:21:26.598244
2024-07-21 11:21:26,599 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-21 11:21:26,599 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-21 11:21:26,599 - INFO - Scheduler started
2024-07-21 11:21:26,599 - INFO - Current time of the scheduler: 2024-07-21 11:21:26.599755
2024-07-21 11:21:26,599 - INFO - Ending scheduler
2024-07-21 11:21:28,950 - INFO - Starting scheduler
2024-07-21 11:21:28,950 - INFO - Updater date and time: 2024-07-21 11:21:28.950595
2024-07-21 11:21:28,951 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-21 11:21:28,951 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-21 11:21:28,951 - INFO - Scheduler started
2024-07-21 11:21:28,952 - INFO - Current time of the scheduler: 2024-07-21 11:21:28.952596
2024-07-21 11:21:28,952 - INFO - Ending scheduler
2024-07-21 11:21:28,972 - INFO - Watching for file changes with StatReloader
2024-07-21 11:26:00,008 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-21 11:26:00 BST)" (scheduled at 2024-07-21 11:26:00+01:00)
2024-07-21 11:26:00,009 - INFO - Inside the procedure sequence
2024-07-21 11:26:00,009 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-21 11:31:00 BST)" (scheduled at 2024-07-21 11:26:00+01:00)
2024-07-21 11:26:00,009 - INFO - Inside the procedure sequence
2024-07-21 11:26:00,168 - INFO - The input start time: 2024-07-21 10:00:00
2024-07-21 11:26:00,168 - INFO - The input start time: 2024-07-21 10:00:00
2024-07-21 11:26:00,760 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-21 11:31:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 72, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-07-21 11:26:06,499 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-21 11:31:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    comparison_comment, general_ticker_info, send_email_enabled = run_model_predictions(ticker)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 369, in run_model_predictions
    pred_reverse_v4, _, _, _ = standard_analysis(model_ticker, "v4")
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 268, in standard_analysis
    write_to_json(pred_reverse, ticker, f"{ticker}_pred_reverse_{model_version}.json")
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\access_results.py", line 44, in write_to_json
    json.dump(data, json_file, indent=4)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2024-07-21 20:06:53,596 - INFO - Starting scheduler
2024-07-21 20:06:53,597 - INFO - Updater date and time: 2024-07-21 20:06:53.597435
2024-07-21 20:06:53,598 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-21 20:06:53,598 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-21 20:06:53,598 - INFO - Scheduler started
2024-07-21 20:06:53,598 - INFO - Current time of the scheduler: 2024-07-21 20:06:53.598437
2024-07-21 20:06:53,599 - INFO - Ending scheduler
2024-07-21 20:06:55,820 - INFO - Starting scheduler
2024-07-21 20:06:55,820 - INFO - Updater date and time: 2024-07-21 20:06:55.820354
2024-07-21 20:06:55,821 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-21 20:06:55,822 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-21 20:06:55,822 - INFO - Scheduler started
2024-07-21 20:06:55,822 - INFO - Current time of the scheduler: 2024-07-21 20:06:55.822354
2024-07-21 20:06:55,822 - INFO - Ending scheduler
2024-07-21 20:06:55,842 - INFO - Watching for file changes with StatReloader
2024-07-26 18:42:58,657 - INFO - Watching for file changes with StatReloader
2024-07-26 18:44:18,946 - INFO - Starting scheduler
2024-07-26 18:44:18,947 - INFO - Updater date and time: 2024-07-26 18:44:18.946185
2024-07-26 18:44:18,948 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 18:44:18,948 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 18:44:18,948 - INFO - Scheduler started
2024-07-26 18:44:18,949 - INFO - Current time of the scheduler: 2024-07-26 18:44:18.949627
2024-07-26 18:44:18,949 - INFO - Ending scheduler
2024-07-26 18:44:21,370 - INFO - Starting scheduler
2024-07-26 18:44:21,370 - INFO - Updater date and time: 2024-07-26 18:44:21.370454
2024-07-26 18:44:21,372 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 18:44:21,372 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 18:44:21,372 - INFO - Scheduler started
2024-07-26 18:44:21,372 - INFO - Current time of the scheduler: 2024-07-26 18:44:21.372885
2024-07-26 18:44:21,372 - INFO - Ending scheduler
2024-07-26 18:44:21,392 - INFO - Watching for file changes with StatReloader
2024-07-26 18:44:22,985 - WARNING - Not Found: /images/favicon.ico
2024-07-26 18:44:25,710 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 214, in ml_report
    pred_reverse_v4 = read_prediction_from_json(model_ticker, f'{model_ticker}_pred_reverse_v4.json')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\access_results.py", line 71, in read_prediction_from_json
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 81 column 12 (char 1942)
2024-07-26 18:44:25,836 - WARNING - Not Found: /favicon.ico
2024-07-26 18:49:38,491 - INFO - Starting scheduler
2024-07-26 18:49:38,492 - INFO - Updater date and time: 2024-07-26 18:49:38.492463
2024-07-26 18:49:38,493 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 18:49:38,493 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 18:49:38,493 - INFO - Scheduler started
2024-07-26 18:49:38,494 - INFO - Current time of the scheduler: 2024-07-26 18:49:38.494464
2024-07-26 18:49:38,494 - INFO - Ending scheduler
2024-07-26 18:49:40,718 - INFO - Starting scheduler
2024-07-26 18:49:40,718 - INFO - Updater date and time: 2024-07-26 18:49:40.718136
2024-07-26 18:49:40,719 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 18:49:40,719 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 18:49:40,719 - INFO - Scheduler started
2024-07-26 18:49:40,720 - INFO - Current time of the scheduler: 2024-07-26 18:49:40.720156
2024-07-26 18:49:40,720 - INFO - Ending scheduler
2024-07-26 18:49:40,742 - INFO - Watching for file changes with StatReloader
2024-07-26 18:49:48,884 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-07-26 18:58:50,668 - INFO - Starting scheduler
2024-07-26 18:58:50,669 - INFO - Updater date and time: 2024-07-26 18:58:50.669488
2024-07-26 18:58:50,670 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 18:58:50,670 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 18:58:50,670 - INFO - Scheduler started
2024-07-26 18:58:50,671 - INFO - Current time of the scheduler: 2024-07-26 18:58:50.671473
2024-07-26 18:58:50,671 - INFO - Ending scheduler
2024-07-26 18:58:52,940 - INFO - Starting scheduler
2024-07-26 18:58:52,940 - INFO - Updater date and time: 2024-07-26 18:58:52.940017
2024-07-26 18:58:52,941 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 18:58:52,941 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 18:58:52,941 - INFO - Scheduler started
2024-07-26 18:58:52,942 - INFO - Current time of the scheduler: 2024-07-26 18:58:52.942035
2024-07-26 18:58:52,942 - INFO - Ending scheduler
2024-07-26 18:58:52,962 - INFO - Watching for file changes with StatReloader
2024-07-26 18:59:12,165 - WARNING - Not Found: /ml_models/ml-report2/images/favicon.ico
2024-07-26 18:59:52,690 - WARNING - Not Found: /tickers/images/favicon.ico
2024-07-26 18:59:57,293 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-07-26 18:59:58,466 - WARNING - Not Found: /prices/update-price/868e4aec-9141-410c-a612-3e282b9e2c38/images/favicon.ico
2024-07-26 19:00:07,670 - ERROR - Internal Server Error: /prices/update-price/868e4aec-9141-410c-a612-3e282b9e2c38/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 58, in updatePrice
    run_model_predictions(price_instance.ticker.symbol)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 369, in run_model_predictions
    pred_reverse_v4, _, _, _ = standard_analysis(model_ticker, "v4")
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 268, in standard_analysis
    write_to_json(pred_reverse, ticker, f"{ticker}_pred_reverse_{model_version}.json")
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\access_results.py", line 44, in write_to_json
    json.dump(data, json_file, indent=4)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2024-07-26 19:06:46,137 - INFO - Starting scheduler
2024-07-26 19:06:46,138 - INFO - Updater date and time: 2024-07-26 19:06:46.138354
2024-07-26 19:06:46,139 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:06:46,139 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:06:46,139 - INFO - Scheduler started
2024-07-26 19:06:46,140 - INFO - Current time of the scheduler: 2024-07-26 19:06:46.140355
2024-07-26 19:06:46,140 - INFO - Ending scheduler
2024-07-26 19:06:48,523 - INFO - Starting scheduler
2024-07-26 19:06:48,524 - INFO - Updater date and time: 2024-07-26 19:06:48.524457
2024-07-26 19:06:48,525 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:06:48,525 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:06:48,525 - INFO - Scheduler started
2024-07-26 19:06:48,525 - INFO - Current time of the scheduler: 2024-07-26 19:06:48.525456
2024-07-26 19:06:48,526 - INFO - Ending scheduler
2024-07-26 19:06:48,544 - INFO - Watching for file changes with StatReloader
2024-07-26 19:06:59,407 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 214, in ml_report
    pred_reverse_v4 = read_prediction_from_json(model_ticker, f'{model_ticker}_pred_reverse_v4.json')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\access_results.py", line 71, in read_prediction_from_json
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 81 column 12 (char 1942)
2024-07-26 19:07:03,385 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-07-26 19:07:21,596 - ERROR - Internal Server Error: /prices/update-price/868e4aec-9141-410c-a612-3e282b9e2c38/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 58, in updatePrice
    run_model_predictions(price_instance.ticker.symbol)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 369, in run_model_predictions
    pred_reverse_v4, _, _, _ = standard_analysis(model_ticker, "v4")
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 268, in standard_analysis
    write_to_json(pred_reverse, ticker, f"{ticker}_pred_reverse_{model_version}.json")
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\access_results.py", line 44, in write_to_json
    json.dump(data, json_file, indent=4)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
2024-07-26 19:09:26,577 - INFO - Starting scheduler
2024-07-26 19:09:26,577 - INFO - Updater date and time: 2024-07-26 19:09:26.577624
2024-07-26 19:09:26,578 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:09:26,578 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:09:26,578 - INFO - Scheduler started
2024-07-26 19:09:26,579 - INFO - Current time of the scheduler: 2024-07-26 19:09:26.578646
2024-07-26 19:09:26,579 - INFO - Ending scheduler
2024-07-26 19:09:28,981 - INFO - Starting scheduler
2024-07-26 19:09:28,981 - INFO - Updater date and time: 2024-07-26 19:09:28.981441
2024-07-26 19:09:28,982 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:09:28,982 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:09:28,982 - INFO - Scheduler started
2024-07-26 19:09:28,983 - INFO - Current time of the scheduler: 2024-07-26 19:09:28.983442
2024-07-26 19:09:28,983 - INFO - Ending scheduler
2024-07-26 19:09:29,002 - INFO - Watching for file changes with StatReloader
2024-07-26 19:19:29,436 - INFO - Starting scheduler
2024-07-26 19:19:29,436 - INFO - Updater date and time: 2024-07-26 19:19:29.436615
2024-07-26 19:19:29,437 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:19:29,437 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:19:29,438 - INFO - Scheduler started
2024-07-26 19:19:29,438 - INFO - Current time of the scheduler: 2024-07-26 19:19:29.438630
2024-07-26 19:19:29,438 - INFO - Ending scheduler
2024-07-26 19:19:31,752 - INFO - Starting scheduler
2024-07-26 19:19:31,753 - INFO - Updater date and time: 2024-07-26 19:19:31.753917
2024-07-26 19:19:31,754 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:19:31,754 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:19:31,754 - INFO - Scheduler started
2024-07-26 19:19:31,755 - INFO - Current time of the scheduler: 2024-07-26 19:19:31.755918
2024-07-26 19:19:31,755 - INFO - Ending scheduler
2024-07-26 19:19:31,774 - INFO - Watching for file changes with StatReloader
2024-07-26 19:19:33,971 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\users\views.py", line 11, in home
    return render(request, 'home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'ml-report' not found. 'ml-report' is not a valid view function or pattern name.
2024-07-26 19:20:08,467 - INFO - Starting scheduler
2024-07-26 19:20:08,468 - INFO - Updater date and time: 2024-07-26 19:20:08.467573
2024-07-26 19:20:08,468 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:20:08,469 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:20:08,469 - INFO - Scheduler started
2024-07-26 19:20:08,469 - INFO - Current time of the scheduler: 2024-07-26 19:20:08.469573
2024-07-26 19:20:08,469 - INFO - Ending scheduler
2024-07-26 19:20:10,544 - INFO - Starting scheduler
2024-07-26 19:20:10,544 - INFO - Updater date and time: 2024-07-26 19:20:10.544980
2024-07-26 19:20:10,545 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:20:10,545 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:20:10,545 - INFO - Scheduler started
2024-07-26 19:20:10,546 - INFO - Current time of the scheduler: 2024-07-26 19:20:10.546981
2024-07-26 19:20:10,546 - INFO - Ending scheduler
2024-07-26 19:20:10,565 - INFO - Watching for file changes with StatReloader
2024-07-26 19:20:11,826 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\users\views.py", line 11, in home
    return render(request, 'home.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'ml-report' not found. 'ml-report' is not a valid view function or pattern name.
2024-07-26 19:21:01,273 - INFO - Starting scheduler
2024-07-26 19:21:01,274 - INFO - Updater date and time: 2024-07-26 19:21:01.274285
2024-07-26 19:21:01,275 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:21:01,275 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:21:01,275 - INFO - Scheduler started
2024-07-26 19:21:01,276 - INFO - Current time of the scheduler: 2024-07-26 19:21:01.276286
2024-07-26 19:21:01,276 - INFO - Ending scheduler
2024-07-26 19:21:03,497 - INFO - Starting scheduler
2024-07-26 19:21:03,497 - INFO - Updater date and time: 2024-07-26 19:21:03.497144
2024-07-26 19:21:03,498 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:21:03,498 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:21:03,499 - INFO - Scheduler started
2024-07-26 19:21:03,499 - INFO - Current time of the scheduler: 2024-07-26 19:21:03.499145
2024-07-26 19:21:03,499 - INFO - Ending scheduler
2024-07-26 19:21:03,521 - INFO - Watching for file changes with StatReloader
2024-07-26 19:47:54,499 - INFO - Starting scheduler
2024-07-26 19:47:54,499 - INFO - Updater date and time: 2024-07-26 19:47:54.499578
2024-07-26 19:47:54,500 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:47:54,501 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:47:54,501 - INFO - Scheduler started
2024-07-26 19:47:54,501 - INFO - Current time of the scheduler: 2024-07-26 19:47:54.501581
2024-07-26 19:47:54,501 - INFO - Ending scheduler
2024-07-26 19:47:56,607 - INFO - Starting scheduler
2024-07-26 19:47:56,608 - INFO - Updater date and time: 2024-07-26 19:47:56.608890
2024-07-26 19:47:56,609 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 19:47:56,609 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 19:47:56,609 - INFO - Scheduler started
2024-07-26 19:47:56,610 - INFO - Current time of the scheduler: 2024-07-26 19:47:56.610892
2024-07-26 19:47:56,610 - INFO - Ending scheduler
2024-07-26 19:47:56,632 - INFO - Watching for file changes with StatReloader
2024-07-26 20:04:52,919 - INFO - Starting scheduler
2024-07-26 20:04:52,920 - INFO - Updater date and time: 2024-07-26 20:04:52.920094
2024-07-26 20:04:52,921 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:04:52,921 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:04:52,921 - INFO - Scheduler started
2024-07-26 20:04:52,922 - INFO - Current time of the scheduler: 2024-07-26 20:04:52.922073
2024-07-26 20:04:52,922 - INFO - Ending scheduler
2024-07-26 20:04:55,286 - INFO - Starting scheduler
2024-07-26 20:04:55,287 - INFO - Updater date and time: 2024-07-26 20:04:55.287135
2024-07-26 20:04:55,288 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:04:55,288 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:04:55,288 - INFO - Scheduler started
2024-07-26 20:04:55,289 - INFO - Current time of the scheduler: 2024-07-26 20:04:55.289134
2024-07-26 20:04:55,289 - INFO - Ending scheduler
2024-07-26 20:04:55,314 - INFO - Watching for file changes with StatReloader
2024-07-26 20:06:00,005 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-26 20:11:00 BST)" (scheduled at 2024-07-26 20:06:00+01:00)
2024-07-26 20:06:00,007 - INFO - Inside the procedure sequence
2024-07-26 20:06:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-26 20:06:00 BST)" (scheduled at 2024-07-26 20:06:00+01:00)
2024-07-26 20:06:00,009 - INFO - Inside the procedure sequence
2024-07-26 20:06:00,288 - INFO - The input start time: 2024-07-26 19:00:00
2024-07-26 20:06:00,288 - INFO - The input start time: 2024-07-26 19:00:00
2024-07-26 20:06:01,254 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-26 20:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 72, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-07-26 20:06:17,499 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-26 20:11:00 BST)" executed successfully
2024-07-26 20:07:25,664 - INFO - Starting scheduler
2024-07-26 20:07:25,665 - INFO - Updater date and time: 2024-07-26 20:07:25.665083
2024-07-26 20:07:25,666 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:07:25,666 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:07:25,666 - INFO - Scheduler started
2024-07-26 20:07:25,667 - INFO - Current time of the scheduler: 2024-07-26 20:07:25.667083
2024-07-26 20:07:25,667 - INFO - Ending scheduler
2024-07-26 20:07:28,036 - INFO - Starting scheduler
2024-07-26 20:07:28,037 - INFO - Updater date and time: 2024-07-26 20:07:28.037004
2024-07-26 20:07:28,038 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:07:28,038 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:07:28,038 - INFO - Scheduler started
2024-07-26 20:07:28,038 - INFO - Current time of the scheduler: 2024-07-26 20:07:28.038024
2024-07-26 20:07:28,038 - INFO - Ending scheduler
2024-07-26 20:07:28,056 - INFO - Watching for file changes with StatReloader
2024-07-26 20:07:32,322 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 416, in ml_report2
    date = original_date.strftime("%B %d, %Y, %-I:%M %p")
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'strftime'
2024-07-26 20:08:15,957 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-07-26 20:08:19,036 - INFO - Starting scheduler
2024-07-26 20:08:19,036 - INFO - Updater date and time: 2024-07-26 20:08:19.036535
2024-07-26 20:08:19,037 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:08:19,038 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:08:19,038 - INFO - Scheduler started
2024-07-26 20:08:19,038 - INFO - Current time of the scheduler: 2024-07-26 20:08:19.038533
2024-07-26 20:08:19,038 - INFO - Ending scheduler
2024-07-26 20:08:19,058 - INFO - Watching for file changes with StatReloader
2024-07-26 20:08:24,242 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-07-26 20:08:26,978 - INFO - Starting scheduler
2024-07-26 20:08:26,979 - INFO - Updater date and time: 2024-07-26 20:08:26.979048
2024-07-26 20:08:26,980 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:08:26,980 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:08:26,980 - INFO - Scheduler started
2024-07-26 20:08:26,981 - INFO - Current time of the scheduler: 2024-07-26 20:08:26.981041
2024-07-26 20:08:26,981 - INFO - Ending scheduler
2024-07-26 20:08:27,000 - INFO - Watching for file changes with StatReloader
2024-07-26 20:10:03,470 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-07-26 20:10:06,451 - INFO - Starting scheduler
2024-07-26 20:10:06,452 - INFO - Updater date and time: 2024-07-26 20:10:06.452454
2024-07-26 20:10:06,453 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:10:06,453 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:10:06,453 - INFO - Scheduler started
2024-07-26 20:10:06,454 - INFO - Current time of the scheduler: 2024-07-26 20:10:06.454454
2024-07-26 20:10:06,454 - INFO - Ending scheduler
2024-07-26 20:10:06,473 - INFO - Watching for file changes with StatReloader
2024-07-26 20:10:11,583 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 413, in ml_report2
    original_date = datetime.pred_historical_v4['pred_historical'][0]['date']
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'pred_historical_v4'
2024-07-26 20:11:00,010 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-26 20:11:00 BST)" (scheduled at 2024-07-26 20:11:00+01:00)
2024-07-26 20:11:00,010 - INFO - Inside the procedure sequence
2024-07-26 20:11:00,010 - INFO - Inside the procedure sequence
2024-07-26 20:11:00,192 - INFO - The input start time: 2024-07-26 19:00:00
2024-07-26 20:11:00,192 - INFO - The input start time: 2024-07-26 19:00:00
2024-07-26 20:11:09,361 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-07-26 20:11:15,603 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 413, in ml_report2
    original_date_str = datetime.pred_historical_v4['pred_historical'][0]['date']
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'pred_historical_v4'
2024-07-26 20:11:17,487 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-26 20:16:00 BST)" executed successfully
2024-07-26 20:11:17,745 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-26 20:16:00 BST)" executed successfully
2024-07-26 20:12:12,946 - INFO - Starting scheduler
2024-07-26 20:12:12,947 - INFO - Updater date and time: 2024-07-26 20:12:12.947345
2024-07-26 20:12:12,948 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:12:12,948 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:12:12,948 - INFO - Scheduler started
2024-07-26 20:12:12,948 - INFO - Current time of the scheduler: 2024-07-26 20:12:12.948345
2024-07-26 20:12:12,948 - INFO - Ending scheduler
2024-07-26 20:12:15,151 - INFO - Starting scheduler
2024-07-26 20:12:15,152 - INFO - Updater date and time: 2024-07-26 20:12:15.152502
2024-07-26 20:12:15,153 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:12:15,153 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:12:15,153 - INFO - Scheduler started
2024-07-26 20:12:15,154 - INFO - Current time of the scheduler: 2024-07-26 20:12:15.154500
2024-07-26 20:12:15,154 - INFO - Ending scheduler
2024-07-26 20:12:15,171 - INFO - Watching for file changes with StatReloader
2024-07-26 20:12:18,592 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 419, in ml_report2
    formatted_date_str = original_date.strftime("%B %d, %Y, %-I:%M %p")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
2024-07-26 20:14:30,702 - INFO - Starting scheduler
2024-07-26 20:14:30,703 - INFO - Updater date and time: 2024-07-26 20:14:30.703458
2024-07-26 20:14:30,704 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:14:30,704 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:14:30,704 - INFO - Scheduler started
2024-07-26 20:14:30,704 - INFO - Current time of the scheduler: 2024-07-26 20:14:30.704458
2024-07-26 20:14:30,704 - INFO - Ending scheduler
2024-07-26 20:14:32,906 - INFO - Starting scheduler
2024-07-26 20:14:32,907 - INFO - Updater date and time: 2024-07-26 20:14:32.907792
2024-07-26 20:14:32,908 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:14:32,908 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:14:32,908 - INFO - Scheduler started
2024-07-26 20:14:32,908 - INFO - Current time of the scheduler: 2024-07-26 20:14:32.908793
2024-07-26 20:14:32,908 - INFO - Ending scheduler
2024-07-26 20:14:32,925 - INFO - Watching for file changes with StatReloader
2024-07-26 20:14:37,135 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 419, in ml_report2
    date = original_date.strftime("%B %d, %Y, %-I:%M %p")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
2024-07-26 20:17:15,024 - INFO - Starting scheduler
2024-07-26 20:17:15,025 - INFO - Updater date and time: 2024-07-26 20:17:15.025694
2024-07-26 20:17:15,026 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:17:15,026 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:17:15,026 - INFO - Scheduler started
2024-07-26 20:17:15,026 - INFO - Current time of the scheduler: 2024-07-26 20:17:15.026694
2024-07-26 20:17:15,027 - INFO - Ending scheduler
2024-07-26 20:17:17,182 - INFO - Starting scheduler
2024-07-26 20:17:17,183 - INFO - Updater date and time: 2024-07-26 20:17:17.183988
2024-07-26 20:17:17,184 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:17:17,184 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:17:17,184 - INFO - Scheduler started
2024-07-26 20:17:17,185 - INFO - Current time of the scheduler: 2024-07-26 20:17:17.185989
2024-07-26 20:17:17,185 - INFO - Ending scheduler
2024-07-26 20:17:17,203 - INFO - Watching for file changes with StatReloader
2024-07-26 20:17:21,376 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 414, in ml_report2
    original_date = datetime.strptime(original_date_str, "%d-%m-%Y %H:%M:%S")
                    ^^^^^^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'strptime'
2024-07-26 20:17:37,555 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-07-26 20:17:40,356 - INFO - Starting scheduler
2024-07-26 20:17:40,356 - INFO - Updater date and time: 2024-07-26 20:17:40.356934
2024-07-26 20:17:40,357 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:17:40,357 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:17:40,357 - INFO - Scheduler started
2024-07-26 20:17:40,358 - INFO - Current time of the scheduler: 2024-07-26 20:17:40.358976
2024-07-26 20:17:40,358 - INFO - Ending scheduler
2024-07-26 20:17:40,376 - INFO - Watching for file changes with StatReloader
2024-07-26 20:17:52,003 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 417, in ml_report2
    date = original_date.strftime("%B %d, %Y, %-I:%M %p")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
2024-07-26 20:22:26,965 - INFO - Starting scheduler
2024-07-26 20:22:26,966 - INFO - Updater date and time: 2024-07-26 20:22:26.966232
2024-07-26 20:22:26,967 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:22:26,967 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:22:26,967 - INFO - Scheduler started
2024-07-26 20:22:26,968 - INFO - Current time of the scheduler: 2024-07-26 20:22:26.968232
2024-07-26 20:22:26,968 - INFO - Ending scheduler
2024-07-26 20:22:29,037 - INFO - Starting scheduler
2024-07-26 20:22:29,038 - INFO - Updater date and time: 2024-07-26 20:22:29.038281
2024-07-26 20:22:29,039 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:22:29,039 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:22:29,039 - INFO - Scheduler started
2024-07-26 20:22:29,040 - INFO - Current time of the scheduler: 2024-07-26 20:22:29.040304
2024-07-26 20:22:29,040 - INFO - Ending scheduler
2024-07-26 20:22:29,058 - INFO - Watching for file changes with StatReloader
2024-07-26 20:23:05,431 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-07-26 20:23:08,505 - INFO - Starting scheduler
2024-07-26 20:23:08,505 - INFO - Updater date and time: 2024-07-26 20:23:08.505998
2024-07-26 20:23:08,506 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:23:08,506 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:23:08,506 - INFO - Scheduler started
2024-07-26 20:23:08,506 - INFO - Current time of the scheduler: 2024-07-26 20:23:08.506998
2024-07-26 20:23:08,507 - INFO - Ending scheduler
2024-07-26 20:23:08,529 - INFO - Watching for file changes with StatReloader
2024-07-26 20:48:15,977 - INFO - Starting scheduler
2024-07-26 20:48:15,978 - INFO - Updater date and time: 2024-07-26 20:48:15.978342
2024-07-26 20:48:15,979 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:48:15,979 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:48:15,979 - INFO - Scheduler started
2024-07-26 20:48:15,979 - INFO - Current time of the scheduler: 2024-07-26 20:48:15.979343
2024-07-26 20:48:15,979 - INFO - Ending scheduler
2024-07-26 20:48:18,310 - INFO - Starting scheduler
2024-07-26 20:48:18,311 - INFO - Updater date and time: 2024-07-26 20:48:18.311002
2024-07-26 20:48:18,312 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:48:18,312 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:48:18,312 - INFO - Scheduler started
2024-07-26 20:48:18,313 - INFO - Current time of the scheduler: 2024-07-26 20:48:18.313060
2024-07-26 20:48:18,313 - INFO - Ending scheduler
2024-07-26 20:48:18,329 - INFO - Watching for file changes with StatReloader
2024-07-26 20:51:51,154 - INFO - Starting scheduler
2024-07-26 20:51:51,154 - INFO - Updater date and time: 2024-07-26 20:51:51.154480
2024-07-26 20:51:51,155 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:51:51,155 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:51:51,155 - INFO - Scheduler started
2024-07-26 20:51:51,156 - INFO - Current time of the scheduler: 2024-07-26 20:51:51.156485
2024-07-26 20:51:51,156 - INFO - Ending scheduler
2024-07-26 20:51:53,715 - INFO - Starting scheduler
2024-07-26 20:51:53,715 - INFO - Updater date and time: 2024-07-26 20:51:53.715106
2024-07-26 20:51:53,716 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 20:51:53,716 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 20:51:53,716 - INFO - Scheduler started
2024-07-26 20:51:53,717 - INFO - Current time of the scheduler: 2024-07-26 20:51:53.717107
2024-07-26 20:51:53,717 - INFO - Ending scheduler
2024-07-26 20:51:53,740 - INFO - Watching for file changes with StatReloader
2024-07-26 20:51:55,286 - WARNING - Not Found: /images/favicon.ico
2024-07-26 20:52:04,239 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-07-26 20:53:29,958 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 411, in ml_report2
    original_date_str = pred_historical_v4['pred_historical'][0]['date']
                        ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'pred_historical'
2024-07-26 20:53:30,052 - WARNING - Not Found: /favicon.ico
2024-07-26 21:04:19,109 - INFO - Starting scheduler
2024-07-26 21:04:19,109 - INFO - Updater date and time: 2024-07-26 21:04:19.109213
2024-07-26 21:04:19,110 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 21:04:19,110 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 21:04:19,111 - INFO - Scheduler started
2024-07-26 21:04:19,111 - INFO - Current time of the scheduler: 2024-07-26 21:04:19.111228
2024-07-26 21:04:19,111 - INFO - Ending scheduler
2024-07-26 21:04:21,265 - INFO - Starting scheduler
2024-07-26 21:04:21,265 - INFO - Updater date and time: 2024-07-26 21:04:21.265541
2024-07-26 21:04:21,266 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-26 21:04:21,266 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-26 21:04:21,266 - INFO - Scheduler started
2024-07-26 21:04:21,267 - INFO - Current time of the scheduler: 2024-07-26 21:04:21.267564
2024-07-26 21:04:21,267 - INFO - Ending scheduler
2024-07-26 21:04:21,286 - INFO - Watching for file changes with StatReloader
2024-07-26 21:04:22,693 - WARNING - Not Found: /images/favicon.ico
2024-07-26 21:04:30,547 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-07-26 21:06:00,010 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-26 21:06:00 BST)" (scheduled at 2024-07-26 21:06:00+01:00)
2024-07-26 21:06:00,010 - INFO - Inside the procedure sequence
2024-07-26 21:06:00,011 - INFO - Inside the procedure sequence
2024-07-26 21:06:00,164 - INFO - The input start time: 2024-07-26 20:00:00
2024-07-26 21:06:00,165 - INFO - The input start time: 2024-07-26 20:00:00
2024-07-26 21:06:15,819 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-26 21:11:00 BST)" executed successfully
2024-07-26 21:06:16,304 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-26 21:11:00 BST)" executed successfully
2024-07-27 08:17:31,383 - INFO - Starting scheduler
2024-07-27 08:17:31,383 - INFO - Updater date and time: 2024-07-27 08:17:31.383131
2024-07-27 08:17:31,385 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:17:31,385 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:17:31,385 - INFO - Scheduler started
2024-07-27 08:17:31,385 - INFO - Current time of the scheduler: 2024-07-27 08:17:31.385167
2024-07-27 08:17:31,386 - INFO - Ending scheduler
2024-07-27 08:17:33,825 - INFO - Starting scheduler
2024-07-27 08:17:33,826 - INFO - Updater date and time: 2024-07-27 08:17:33.826409
2024-07-27 08:17:33,827 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:17:33,828 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:17:33,828 - INFO - Scheduler started
2024-07-27 08:17:33,828 - INFO - Current time of the scheduler: 2024-07-27 08:17:33.828273
2024-07-27 08:17:33,828 - INFO - Ending scheduler
2024-07-27 08:17:33,852 - INFO - Watching for file changes with StatReloader
2024-07-27 08:17:35,603 - WARNING - Not Found: /images/favicon.ico
2024-07-27 08:17:39,211 - WARNING - Not Found: /ml_models/model-accuracy/images/favicon.ico
2024-07-27 08:18:30,819 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:18:34,339 - INFO - Starting scheduler
2024-07-27 08:18:34,341 - INFO - Updater date and time: 2024-07-27 08:18:34.340312
2024-07-27 08:18:34,342 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:18:34,342 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:18:34,342 - INFO - Scheduler started
2024-07-27 08:18:34,343 - INFO - Current time of the scheduler: 2024-07-27 08:18:34.343396
2024-07-27 08:18:34,343 - INFO - Ending scheduler
2024-07-27 08:18:34,367 - INFO - Watching for file changes with StatReloader
2024-07-27 08:19:38,896 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:19:42,398 - INFO - Starting scheduler
2024-07-27 08:19:42,399 - INFO - Updater date and time: 2024-07-27 08:19:42.399793
2024-07-27 08:19:42,400 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:19:42,400 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:19:42,400 - INFO - Scheduler started
2024-07-27 08:19:42,401 - INFO - Current time of the scheduler: 2024-07-27 08:19:42.401797
2024-07-27 08:19:42,401 - INFO - Ending scheduler
2024-07-27 08:19:42,427 - INFO - Watching for file changes with StatReloader
2024-07-27 08:20:02,696 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:20:05,987 - INFO - Starting scheduler
2024-07-27 08:20:05,988 - INFO - Updater date and time: 2024-07-27 08:20:05.988442
2024-07-27 08:20:05,989 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:20:05,989 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:20:05,989 - INFO - Scheduler started
2024-07-27 08:20:05,989 - INFO - Current time of the scheduler: 2024-07-27 08:20:05.989441
2024-07-27 08:20:05,990 - INFO - Ending scheduler
2024-07-27 08:20:06,014 - INFO - Watching for file changes with StatReloader
2024-07-27 08:20:43,811 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:20:47,292 - INFO - Starting scheduler
2024-07-27 08:20:47,294 - INFO - Updater date and time: 2024-07-27 08:20:47.293985
2024-07-27 08:20:47,294 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:20:47,294 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:20:47,294 - INFO - Scheduler started
2024-07-27 08:20:47,295 - INFO - Current time of the scheduler: 2024-07-27 08:20:47.295966
2024-07-27 08:20:47,295 - INFO - Ending scheduler
2024-07-27 08:20:47,325 - INFO - Watching for file changes with StatReloader
2024-07-27 08:21:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:21:00 BST)" (scheduled at 2024-07-27 08:21:00+01:00)
2024-07-27 08:21:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:26:00 BST)" (scheduled at 2024-07-27 08:21:00+01:00)
2024-07-27 08:21:00,015 - INFO - Inside the procedure sequence
2024-07-27 08:21:00,015 - INFO - Inside the procedure sequence
2024-07-27 08:21:00,293 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:21:00,293 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:21:01,192 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:26:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 72, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-07-27 08:21:01,206 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:26:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 72, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-07-27 08:23:35,398 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:23:38,663 - INFO - Starting scheduler
2024-07-27 08:23:38,664 - INFO - Updater date and time: 2024-07-27 08:23:38.664563
2024-07-27 08:23:38,665 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:23:38,665 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:23:38,666 - INFO - Scheduler started
2024-07-27 08:23:38,666 - INFO - Current time of the scheduler: 2024-07-27 08:23:38.666548
2024-07-27 08:23:38,666 - INFO - Ending scheduler
2024-07-27 08:23:38,694 - INFO - Watching for file changes with StatReloader
2024-07-27 08:25:47,646 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:25:50,885 - INFO - Starting scheduler
2024-07-27 08:25:50,885 - INFO - Updater date and time: 2024-07-27 08:25:50.885140
2024-07-27 08:25:50,887 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:25:50,887 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:25:50,887 - INFO - Scheduler started
2024-07-27 08:25:50,887 - INFO - Current time of the scheduler: 2024-07-27 08:25:50.887655
2024-07-27 08:25:50,887 - INFO - Ending scheduler
2024-07-27 08:25:50,914 - INFO - Watching for file changes with StatReloader
2024-07-27 08:26:00,004 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:31:00 BST)" (scheduled at 2024-07-27 08:26:00+01:00)
2024-07-27 08:26:00,004 - INFO - Inside the procedure sequence
2024-07-27 08:26:00,004 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:31:00 BST)" (scheduled at 2024-07-27 08:26:00+01:00)
2024-07-27 08:26:00,005 - INFO - Inside the procedure sequence
2024-07-27 08:26:00,007 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:26:00,244 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:26:20,308 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:31:00 BST)" executed successfully
2024-07-27 08:26:21,660 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:31:00 BST)" executed successfully
2024-07-27 08:27:27,725 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:27:38,351 - INFO - Starting scheduler
2024-07-27 08:27:38,352 - INFO - Updater date and time: 2024-07-27 08:27:38.351147
2024-07-27 08:27:38,353 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:27:38,353 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:27:38,353 - INFO - Scheduler started
2024-07-27 08:27:38,353 - INFO - Current time of the scheduler: 2024-07-27 08:27:38.353148
2024-07-27 08:27:38,354 - INFO - Ending scheduler
2024-07-27 08:27:40,852 - INFO - Starting scheduler
2024-07-27 08:27:40,853 - INFO - Updater date and time: 2024-07-27 08:27:40.853110
2024-07-27 08:27:40,854 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:27:40,854 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:27:40,854 - INFO - Scheduler started
2024-07-27 08:27:40,855 - INFO - Current time of the scheduler: 2024-07-27 08:27:40.855060
2024-07-27 08:27:40,855 - INFO - Ending scheduler
2024-07-27 08:27:40,880 - INFO - Watching for file changes with StatReloader
2024-07-27 08:27:46,585 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 729, in display_model_accuracy
    model_results, profit_accuracy, trade_accuracy= trade_forecast_assessment(ticker, model_version)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 341, in trade_forecast_assessment
    buy_sell_percentages = calc_matches(y_actual, "model_pred", model_prediction_binary)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 368, in calc_matches
    sell_matches = df[:, 0] == df[:, 1] & df['col_name']==0
                   ~~^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 82, in pandas._libs.index.IndexEngine.get_loc
TypeError: '(slice(None, None, None), 0)' is an invalid key
2024-07-27 08:27:46,737 - WARNING - Not Found: /favicon.ico
2024-07-27 08:28:19,002 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:28:22,421 - INFO - Starting scheduler
2024-07-27 08:28:22,422 - INFO - Updater date and time: 2024-07-27 08:28:22.422106
2024-07-27 08:28:22,423 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:28:22,423 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:28:22,423 - INFO - Scheduler started
2024-07-27 08:28:22,424 - INFO - Current time of the scheduler: 2024-07-27 08:28:22.424098
2024-07-27 08:28:22,424 - INFO - Ending scheduler
2024-07-27 08:28:22,452 - INFO - Watching for file changes with StatReloader
2024-07-27 08:28:25,951 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'col_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 729, in display_model_accuracy
    model_results, profit_accuracy, trade_accuracy= trade_forecast_assessment(ticker, model_version)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 341, in trade_forecast_assessment
    buy_sell_percentages = calc_matches(y_actual, "model_pred", model_prediction_binary)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 368, in calc_matches
    sell_matches = df.iloc[:, 0] == df.iloc[:, 1] & df['col_name']==0
                                                    ~~^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'col_name'
2024-07-27 08:28:43,075 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:28:46,797 - INFO - Starting scheduler
2024-07-27 08:28:46,797 - INFO - Updater date and time: 2024-07-27 08:28:46.797145
2024-07-27 08:28:46,798 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:28:46,799 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:28:46,799 - INFO - Scheduler started
2024-07-27 08:28:46,799 - INFO - Current time of the scheduler: 2024-07-27 08:28:46.799143
2024-07-27 08:28:46,799 - INFO - Ending scheduler
2024-07-27 08:28:46,824 - INFO - Watching for file changes with StatReloader
2024-07-27 08:28:48,620 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 729, in display_model_accuracy
    model_results, profit_accuracy, trade_accuracy= trade_forecast_assessment(ticker, model_version)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 341, in trade_forecast_assessment
    buy_sell_percentages = calc_matches(y_actual, "model_pred", model_prediction_binary)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 368, in calc_matches
    sell_matches = df.iloc[:, 0] == df.iloc[:, 1] & df[col_name]==0
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2024-07-27 08:29:46,899 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:29:50,294 - INFO - Starting scheduler
2024-07-27 08:29:50,295 - INFO - Updater date and time: 2024-07-27 08:29:50.295601
2024-07-27 08:29:50,296 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:29:50,296 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:29:50,296 - INFO - Scheduler started
2024-07-27 08:29:50,297 - INFO - Current time of the scheduler: 2024-07-27 08:29:50.296600
2024-07-27 08:29:50,297 - INFO - Ending scheduler
2024-07-27 08:29:50,323 - INFO - Watching for file changes with StatReloader
2024-07-27 08:30:24,964 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:30:28,205 - INFO - Starting scheduler
2024-07-27 08:30:28,205 - INFO - Updater date and time: 2024-07-27 08:30:28.205160
2024-07-27 08:30:28,206 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:30:28,207 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:30:28,207 - INFO - Scheduler started
2024-07-27 08:30:28,207 - INFO - Current time of the scheduler: 2024-07-27 08:30:28.207266
2024-07-27 08:30:28,207 - INFO - Ending scheduler
2024-07-27 08:30:28,232 - INFO - Watching for file changes with StatReloader
2024-07-27 08:31:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:31:00 BST)" (scheduled at 2024-07-27 08:31:00+01:00)
2024-07-27 08:31:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:36:00 BST)" (scheduled at 2024-07-27 08:31:00+01:00)
2024-07-27 08:31:00,007 - INFO - Inside the procedure sequence
2024-07-27 08:31:00,008 - INFO - Inside the procedure sequence
2024-07-27 08:31:00,175 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:31:00,175 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:31:17,724 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:36:00 BST)" executed successfully
2024-07-27 08:31:18,691 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:36:00 BST)" executed successfully
2024-07-27 08:31:36,856 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:31:50,107 - INFO - Starting scheduler
2024-07-27 08:31:50,108 - INFO - Updater date and time: 2024-07-27 08:31:50.108817
2024-07-27 08:31:50,109 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:31:50,109 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:31:50,109 - INFO - Scheduler started
2024-07-27 08:31:50,110 - INFO - Current time of the scheduler: 2024-07-27 08:31:50.110816
2024-07-27 08:31:50,110 - INFO - Ending scheduler
2024-07-27 08:31:52,841 - INFO - Starting scheduler
2024-07-27 08:31:52,842 - INFO - Updater date and time: 2024-07-27 08:31:52.842672
2024-07-27 08:31:52,844 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:31:52,844 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:31:52,844 - INFO - Scheduler started
2024-07-27 08:31:52,845 - INFO - Current time of the scheduler: 2024-07-27 08:31:52.845144
2024-07-27 08:31:52,845 - INFO - Ending scheduler
2024-07-27 08:31:52,875 - INFO - Watching for file changes with StatReloader
2024-07-27 08:33:08,347 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:33:11,929 - INFO - Starting scheduler
2024-07-27 08:33:11,930 - INFO - Updater date and time: 2024-07-27 08:33:11.930533
2024-07-27 08:33:11,931 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:33:11,931 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:33:11,931 - INFO - Scheduler started
2024-07-27 08:33:11,932 - INFO - Current time of the scheduler: 2024-07-27 08:33:11.932514
2024-07-27 08:33:11,932 - INFO - Ending scheduler
2024-07-27 08:33:11,952 - INFO - Watching for file changes with StatReloader
2024-07-27 08:33:13,404 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 729, in display_model_accuracy
    model_results, profit_accuracy, trade_accuracy= trade_forecast_assessment(ticker, model_version)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 341, in trade_forecast_assessment
    buy_sell_percentages = calc_matches(y_actual_binary, "model_pred", model_prediction_binary)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 365, in calc_matches
    df[col_name] = array
    ~~^^^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
2024-07-27 08:35:11,299 - INFO - Starting scheduler
2024-07-27 08:35:11,299 - INFO - Updater date and time: 2024-07-27 08:35:11.299579
2024-07-27 08:35:11,301 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:35:11,301 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:35:11,301 - INFO - Scheduler started
2024-07-27 08:35:11,301 - INFO - Current time of the scheduler: 2024-07-27 08:35:11.301581
2024-07-27 08:35:11,301 - INFO - Ending scheduler
2024-07-27 08:35:14,108 - INFO - Starting scheduler
2024-07-27 08:35:14,110 - INFO - Updater date and time: 2024-07-27 08:35:14.109887
2024-07-27 08:35:14,111 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:35:14,111 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:35:14,111 - INFO - Scheduler started
2024-07-27 08:35:14,111 - INFO - Current time of the scheduler: 2024-07-27 08:35:14.111019
2024-07-27 08:35:14,111 - INFO - Ending scheduler
2024-07-27 08:35:14,133 - INFO - Watching for file changes with StatReloader
2024-07-27 08:35:20,670 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 729, in display_model_accuracy
    model_results, profit_accuracy, trade_accuracy= trade_forecast_assessment(ticker, model_version)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 341, in trade_forecast_assessment
    buy_sell_percentages = calc_matches(y_actual_binary.flatten(), "model_pred", model_prediction_binary)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 365, in calc_matches
    df[col_name] = array
    ~~^^^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
2024-07-27 08:36:00,010 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:36:00 BST)" (scheduled at 2024-07-27 08:36:00+01:00)
2024-07-27 08:36:00,011 - INFO - Inside the procedure sequence
2024-07-27 08:36:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:36:00 BST)" (scheduled at 2024-07-27 08:36:00+01:00)
2024-07-27 08:36:00,011 - INFO - Inside the procedure sequence
2024-07-27 08:36:00,194 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:36:00,194 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:36:20,452 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:41:00 BST)" executed successfully
2024-07-27 08:36:21,873 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:41:00 BST)" executed successfully
2024-07-27 08:37:54,667 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:38:01,685 - INFO - Starting scheduler
2024-07-27 08:38:01,685 - INFO - Updater date and time: 2024-07-27 08:38:01.685009
2024-07-27 08:38:01,686 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:38:01,687 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:38:01,687 - INFO - Scheduler started
2024-07-27 08:38:01,687 - INFO - Current time of the scheduler: 2024-07-27 08:38:01.687052
2024-07-27 08:38:01,687 - INFO - Ending scheduler
2024-07-27 08:38:04,371 - INFO - Starting scheduler
2024-07-27 08:38:04,372 - INFO - Updater date and time: 2024-07-27 08:38:04.372620
2024-07-27 08:38:04,374 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:38:04,374 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:38:04,374 - INFO - Scheduler started
2024-07-27 08:38:04,375 - INFO - Current time of the scheduler: 2024-07-27 08:38:04.375531
2024-07-27 08:38:04,375 - INFO - Ending scheduler
2024-07-27 08:38:04,401 - INFO - Watching for file changes with StatReloader
2024-07-27 08:38:06,665 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'model_pred'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 729, in display_model_accuracy
    model_results, profit_accuracy, trade_accuracy= trade_forecast_assessment(ticker, model_version)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 341, in trade_forecast_assessment
    buy_sell_percentages = calc_matches(y_actual_binary.flatten(), "model_pred", model_prediction_binary)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 368, in calc_matches
    sell_matches = (df.iloc[:, 0] == df.iloc[:, 1]) & (df[col_name]==0)
                                                       ~~^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'model_pred'
2024-07-27 08:38:28,030 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:38:31,679 - INFO - Starting scheduler
2024-07-27 08:38:31,679 - INFO - Updater date and time: 2024-07-27 08:38:31.679644
2024-07-27 08:38:31,680 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:38:31,680 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:38:31,680 - INFO - Scheduler started
2024-07-27 08:38:31,681 - INFO - Current time of the scheduler: 2024-07-27 08:38:31.681817
2024-07-27 08:38:31,681 - INFO - Ending scheduler
2024-07-27 08:38:31,706 - INFO - Watching for file changes with StatReloader
2024-07-27 08:41:00,002 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:41:00 BST)" (scheduled at 2024-07-27 08:41:00+01:00)
2024-07-27 08:41:00,002 - INFO - Inside the procedure sequence
ence (trigger: interval[0:05:00], next run at: 2024-07-27 08:46:00 BST)" (scheduled at 2024-07-27 08:41:00+01:00)
2024-07-27 08:41:00,002 - INFO - Inside the procedure sequence
2024-07-27 08:41:00,183 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:41:00,184 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:41:00,895 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:46:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 72, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-07-27 08:41:00,899 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:46:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 72, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-07-27 08:41:57,844 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:42:01,174 - INFO - Starting scheduler
2024-07-27 08:42:01,174 - INFO - Updater date and time: 2024-07-27 08:42:01.174541
2024-07-27 08:42:01,175 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:42:01,175 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:42:01,175 - INFO - Scheduler started
2024-07-27 08:42:01,176 - INFO - Current time of the scheduler: 2024-07-27 08:42:01.176541
2024-07-27 08:42:01,176 - INFO - Ending scheduler
2024-07-27 08:42:01,198 - INFO - Watching for file changes with StatReloader
2024-07-27 08:42:12,849 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:42:16,121 - INFO - Starting scheduler
2024-07-27 08:42:16,122 - INFO - Updater date and time: 2024-07-27 08:42:16.121555
2024-07-27 08:42:16,123 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:42:16,123 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:42:16,123 - INFO - Scheduler started
2024-07-27 08:42:16,124 - INFO - Current time of the scheduler: 2024-07-27 08:42:16.124547
2024-07-27 08:42:16,124 - INFO - Ending scheduler
2024-07-27 08:42:16,152 - INFO - Watching for file changes with StatReloader
2024-07-27 08:42:39,566 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:42:42,965 - INFO - Starting scheduler
2024-07-27 08:42:42,966 - INFO - Updater date and time: 2024-07-27 08:42:42.966114
2024-07-27 08:42:42,967 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:42:42,967 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:42:42,967 - INFO - Scheduler started
2024-07-27 08:42:42,967 - INFO - Current time of the scheduler: 2024-07-27 08:42:42.967102
2024-07-27 08:42:42,967 - INFO - Ending scheduler
2024-07-27 08:42:42,986 - INFO - Watching for file changes with StatReloader
2024-07-27 08:43:19,321 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:43:22,787 - INFO - Starting scheduler
2024-07-27 08:43:22,787 - INFO - Updater date and time: 2024-07-27 08:43:22.787681
2024-07-27 08:43:22,789 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:43:22,789 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:43:22,789 - INFO - Scheduler started
2024-07-27 08:43:22,790 - INFO - Current time of the scheduler: 2024-07-27 08:43:22.790012
2024-07-27 08:43:22,790 - INFO - Ending scheduler
2024-07-27 08:43:22,818 - INFO - Watching for file changes with StatReloader
2024-07-27 08:44:37,512 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:44:40,908 - INFO - Starting scheduler
2024-07-27 08:44:40,909 - INFO - Updater date and time: 2024-07-27 08:44:40.909551
2024-07-27 08:44:40,910 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:44:40,910 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:44:40,910 - INFO - Scheduler started
2024-07-27 08:44:40,911 - INFO - Current time of the scheduler: 2024-07-27 08:44:40.911814
2024-07-27 08:44:40,911 - INFO - Ending scheduler
2024-07-27 08:44:40,937 - INFO - Watching for file changes with StatReloader
2024-07-27 08:45:37,656 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-07-27 08:45:40,761 - INFO - Starting scheduler
2024-07-27 08:45:40,762 - INFO - Updater date and time: 2024-07-27 08:45:40.761063
2024-07-27 08:45:40,763 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:45:40,763 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:45:40,763 - INFO - Scheduler started
2024-07-27 08:45:40,764 - INFO - Current time of the scheduler: 2024-07-27 08:45:40.764063
2024-07-27 08:45:40,764 - INFO - Ending scheduler
2024-07-27 08:45:40,791 - INFO - Watching for file changes with StatReloader
2024-07-27 08:45:51,443 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-07-27 08:45:54,505 - INFO - Starting scheduler
2024-07-27 08:45:54,505 - INFO - Updater date and time: 2024-07-27 08:45:54.505121
2024-07-27 08:45:54,506 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:45:54,507 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:45:54,507 - INFO - Scheduler started
2024-07-27 08:45:54,507 - INFO - Current time of the scheduler: 2024-07-27 08:45:54.507182
2024-07-27 08:45:54,507 - INFO - Ending scheduler
2024-07-27 08:45:54,529 - INFO - Watching for file changes with StatReloader
2024-07-27 08:46:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:51:00 BST)" (scheduled at 2024-07-27 08:46:00+01:00)
2024-07-27 08:46:00,015 - INFO - Inside the procedure sequence
2024-07-27 08:46:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:51:00 BST)" (scheduled at 2024-07-27 08:46:00+01:00)
2024-07-27 08:46:00,018 - INFO - Inside the procedure sequence
2024-07-27 08:46:00,018 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:46:00,186 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:46:17,106 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:51:00 BST)" executed successfully
2024-07-27 08:46:18,794 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:51:00 BST)" executed successfully
2024-07-27 08:46:21,888 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-07-27 08:47:38,330 - INFO - Starting scheduler
2024-07-27 08:47:38,331 - INFO - Updater date and time: 2024-07-27 08:47:38.330571
2024-07-27 08:47:38,332 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:47:38,332 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:47:38,332 - INFO - Scheduler started
2024-07-27 08:47:38,332 - INFO - Current time of the scheduler: 2024-07-27 08:47:38.332592
2024-07-27 08:47:38,332 - INFO - Ending scheduler
2024-07-27 08:47:40,884 - INFO - Starting scheduler
2024-07-27 08:47:40,885 - INFO - Updater date and time: 2024-07-27 08:47:40.885038
2024-07-27 08:47:40,887 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:47:40,887 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:47:40,887 - INFO - Scheduler started
2024-07-27 08:47:40,888 - INFO - Current time of the scheduler: 2024-07-27 08:47:40.888036
2024-07-27 08:47:40,888 - INFO - Ending scheduler
2024-07-27 08:47:40,918 - INFO - Watching for file changes with StatReloader
2024-07-27 08:47:43,162 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 729, in display_model_accuracy
    model_results, profit_accuracy, trade_accuracy, buy_sell_split = trade_forecast_assessment(ticker, model_version)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 339, in trade_forecast_assessment
    buy_sell_split = calc_matches(y_actual_binary.flatten(), model_prediction_binary)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 365, in calc_matches
    sell_matches = (df.iloc[:, 0] == df.iloc[:, 1]) & (df[col_name]==0)
                                                          ^^^^^^^^
NameError: name 'col_name' is not defined
2024-07-27 08:48:07,624 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 729, in display_model_accuracy
    model_results, profit_accuracy, trade_accuracy, buy_sell_split = trade_forecast_assessment(ticker, model_version)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 339, in trade_forecast_assessment
    buy_sell_split = calc_matches(y_actual_binary.flatten(), model_prediction_binary)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 365, in calc_matches
    sell_matches = (df.iloc[:, 0] == df.iloc[:, 1]) & (df[col_name]==0)
                                                          ^^^^^^^^
NameError: name 'col_name' is not defined
2024-07-27 08:49:18,710 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 08:49:21,999 - INFO - Starting scheduler
2024-07-27 08:49:21,999 - INFO - Updater date and time: 2024-07-27 08:49:21.999502
2024-07-27 08:49:22,000 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:49:22,001 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:49:22,001 - INFO - Scheduler started
2024-07-27 08:49:22,002 - INFO - Current time of the scheduler: 2024-07-27 08:49:22.002418
2024-07-27 08:49:22,002 - INFO - Ending scheduler
2024-07-27 08:49:22,030 - INFO - Watching for file changes with StatReloader
2024-07-27 08:51:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:51:00 BST)" (scheduled at 2024-07-27 08:51:00+01:00)
2024-07-27 08:51:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:56:00 BST)" (scheduled at 2024-07-27 08:51:00+01:00)
2024-07-27 08:51:00,015 - INFO - Inside the procedure sequence
2024-07-27 08:51:00,015 - INFO - Inside the procedure sequence
2024-07-27 08:51:00,244 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:51:00,245 - INFO - The input start time: 2024-07-27 07:00:00
2024-07-27 08:51:18,150 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:56:00 BST)" executed successfully
2024-07-27 08:51:18,157 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 08:56:00 BST)" executed successfully
2024-07-27 08:53:45,393 - INFO - Starting scheduler
2024-07-27 08:53:45,394 - INFO - Updater date and time: 2024-07-27 08:53:45.394181
2024-07-27 08:53:45,395 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:53:45,396 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:53:45,396 - INFO - Scheduler started
2024-07-27 08:53:45,396 - INFO - Current time of the scheduler: 2024-07-27 08:53:45.396128
2024-07-27 08:53:45,396 - INFO - Ending scheduler
2024-07-27 08:53:47,964 - INFO - Starting scheduler
2024-07-27 08:53:47,965 - INFO - Updater date and time: 2024-07-27 08:53:47.965550
2024-07-27 08:53:47,966 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:53:47,967 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:53:47,967 - INFO - Scheduler started
2024-07-27 08:53:47,967 - INFO - Current time of the scheduler: 2024-07-27 08:53:47.967550
2024-07-27 08:53:47,967 - INFO - Ending scheduler
2024-07-27 08:53:47,993 - INFO - Watching for file changes with StatReloader
2024-07-27 08:53:57,302 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-07-27 08:54:10,682 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 08:54:28,659 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 08:54:31,135 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 08:54:54,683 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 08:57:09,067 - INFO - Starting scheduler
2024-07-27 08:57:09,068 - INFO - Updater date and time: 2024-07-27 08:57:09.068361
2024-07-27 08:57:09,070 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:57:09,070 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:57:09,070 - INFO - Scheduler started
2024-07-27 08:57:09,071 - INFO - Current time of the scheduler: 2024-07-27 08:57:09.071422
2024-07-27 08:57:09,071 - INFO - Ending scheduler
2024-07-27 08:57:11,701 - INFO - Starting scheduler
2024-07-27 08:57:11,701 - INFO - Updater date and time: 2024-07-27 08:57:11.701938
2024-07-27 08:57:11,702 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 08:57:11,702 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 08:57:11,702 - INFO - Scheduler started
2024-07-27 08:57:11,704 - INFO - Current time of the scheduler: 2024-07-27 08:57:11.704146
2024-07-27 08:57:11,704 - INFO - Ending scheduler
2024-07-27 08:57:11,729 - INFO - Watching for file changes with StatReloader
2024-07-27 08:57:17,385 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 08:59:59,374 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 09:00:02,835 - INFO - Starting scheduler
2024-07-27 09:00:02,836 - INFO - Updater date and time: 2024-07-27 09:00:02.836933
2024-07-27 09:00:02,838 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 09:00:02,838 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 09:00:02,838 - INFO - Scheduler started
2024-07-27 09:00:02,838 - INFO - Current time of the scheduler: 2024-07-27 09:00:02.838097
2024-07-27 09:00:02,839 - INFO - Ending scheduler
2024-07-27 09:00:02,859 - INFO - Watching for file changes with StatReloader
2024-07-27 09:00:08,288 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 09:00:47,281 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 09:00:49,844 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 09:01:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 09:01:00 BST)" (scheduled at 2024-07-27 09:01:00+01:00)
2024-07-27 09:01:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 09:01:00 BST)" (scheduled at 2024-07-27 09:01:00+01:00)
2024-07-27 09:01:00,004 - INFO - Inside the procedure sequence
2024-07-27 09:01:00,004 - INFO - Inside the procedure sequence
2024-07-27 09:01:00,177 - INFO - The input start time: 2024-07-27 08:00:00
2024-07-27 09:01:00,177 - INFO - The input start time: 2024-07-27 08:00:00
2024-07-27 09:01:01,024 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 09:06:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 72, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-07-27 09:01:04,882 - WARNING - Not Found: /ml_models/
2024-07-27 09:01:14,520 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 09:01:18,008 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 09:06:00 BST)" executed successfully
2024-07-27 09:05:30,564 - INFO - Starting scheduler
2024-07-27 09:05:30,565 - INFO - Updater date and time: 2024-07-27 09:05:30.565019
2024-07-27 09:05:30,565 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 09:05:30,565 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 09:05:30,566 - INFO - Scheduler started
2024-07-27 09:05:30,567 - INFO - Current time of the scheduler: 2024-07-27 09:05:30.567183
2024-07-27 09:05:30,567 - INFO - Ending scheduler
2024-07-27 09:05:33,420 - INFO - Starting scheduler
2024-07-27 09:05:33,421 - INFO - Updater date and time: 2024-07-27 09:05:33.421198
2024-07-27 09:05:33,421 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 09:05:33,422 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 09:05:33,422 - INFO - Scheduler started
2024-07-27 09:05:33,422 - INFO - Current time of the scheduler: 2024-07-27 09:05:33.422704
2024-07-27 09:05:33,422 - INFO - Ending scheduler
2024-07-27 09:05:33,456 - INFO - Watching for file changes with StatReloader
2024-07-27 09:05:39,549 - WARNING - Not Found: /images/favicon.ico
2024-07-27 09:05:41,912 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 09:05:42,032 - WARNING - Not Found: /favicon.ico
2024-07-27 09:06:00,009 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 09:06:00 BST)" (scheduled at 2024-07-27 09:06:00+01:00)
2024-07-27 09:06:00,009 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 09:06:00 BST)" (scheduled at 2024-07-27 09:06:00+01:00)
2024-07-27 09:06:00,010 - INFO - Inside the procedure sequence
2024-07-27 09:06:00,010 - INFO - Inside the procedure sequence
2024-07-27 09:06:00,166 - INFO - The input start time: 2024-07-27 08:00:00
2024-07-27 09:06:00,166 - INFO - The input start time: 2024-07-27 08:00:00
2024-07-27 09:06:00,826 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 09:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 72, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-07-27 09:06:00,826 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-27 09:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 72, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-07-27 09:07:23,347 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 09:07:26,774 - INFO - Starting scheduler
2024-07-27 09:07:26,774 - INFO - Updater date and time: 2024-07-27 09:07:26.774265
2024-07-27 09:07:26,775 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 09:07:26,776 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 09:07:26,776 - INFO - Scheduler started
2024-07-27 09:07:26,776 - INFO - Current time of the scheduler: 2024-07-27 09:07:26.776301
2024-07-27 09:07:26,776 - INFO - Ending scheduler
2024-07-27 09:07:26,804 - INFO - Watching for file changes with StatReloader
2024-07-27 09:07:27,165 - ERROR - Internal Server Error: /ml_models/model-accuracy/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 736, in display_model_accuracy
    context = {'form': form, "profit_accuracy": profit_accuracy, "trade_accuracy": trade_accuracy, "buy_sell_split": buy_sell_split}
                                                                                                                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'buy_sell_split' where it is not associated with a value
2024-07-27 09:08:15,740 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-07-27 09:08:19,048 - INFO - Starting scheduler
2024-07-27 09:08:19,048 - INFO - Updater date and time: 2024-07-27 09:08:19.048979
2024-07-27 09:08:19,050 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 09:08:19,050 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 09:08:19,050 - INFO - Scheduler started
2024-07-27 09:08:19,051 - INFO - Current time of the scheduler: 2024-07-27 09:08:19.051428
2024-07-27 09:08:19,051 - INFO - Ending scheduler
2024-07-27 09:08:19,083 - INFO - Watching for file changes with StatReloader
2024-07-27 09:08:21,639 - WARNING - Not Found: /ml_models/model-accuracy/images/favicon.ico
2024-07-27 09:08:55,219 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-07-27 09:08:58,813 - INFO - Starting scheduler
2024-07-27 09:08:58,814 - INFO - Updater date and time: 2024-07-27 09:08:58.814915
2024-07-27 09:08:58,816 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 09:08:58,816 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 09:08:58,816 - INFO - Scheduler started
2024-07-27 09:08:58,817 - INFO - Current time of the scheduler: 2024-07-27 09:08:58.817942
2024-07-27 09:08:58,817 - INFO - Ending scheduler
2024-07-27 09:08:58,846 - INFO - Watching for file changes with StatReloader
2024-07-27 09:09:11,092 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-07-27 09:09:11,986 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-07-27 09:09:28,749 - WARNING - Not Found: /tickers/images/favicon.ico
2024-07-27 09:09:32,091 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-07-27 09:09:52,738 - WARNING - Not Found: /ml_models/ml-predictions/images/favicon.ico
2024-07-27 09:13:04,476 - INFO - Starting scheduler
2024-07-27 09:13:04,477 - INFO - Updater date and time: 2024-07-27 09:13:04.477838
2024-07-27 09:13:04,478 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 09:13:04,478 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 09:13:04,478 - INFO - Scheduler started
2024-07-27 09:13:04,479 - INFO - Current time of the scheduler: 2024-07-27 09:13:04.479840
2024-07-27 09:13:04,479 - INFO - Ending scheduler
2024-07-27 09:13:07,228 - INFO - Starting scheduler
2024-07-27 09:13:07,228 - INFO - Updater date and time: 2024-07-27 09:13:07.228762
2024-07-27 09:13:07,229 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-27 09:13:07,229 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-27 09:13:07,229 - INFO - Scheduler started
2024-07-27 09:13:07,230 - INFO - Current time of the scheduler: 2024-07-27 09:13:07.230902
2024-07-27 09:13:07,231 - INFO - Ending scheduler
2024-07-27 09:13:07,267 - INFO - Watching for file changes with StatReloader
2024-07-27 09:14:19,592 - WARNING - Not Found: /profile/images/favicon.ico
2024-07-28 15:13:26,846 - INFO - Starting scheduler
2024-07-28 15:13:26,847 - INFO - Updater date and time: 2024-07-28 15:13:26.847996
2024-07-28 15:13:26,850 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-28 15:13:26,850 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-28 15:13:26,850 - INFO - Scheduler started
2024-07-28 15:13:26,850 - INFO - Current time of the scheduler: 2024-07-28 15:13:26.850047
2024-07-28 15:13:26,850 - INFO - Ending scheduler
2024-07-28 15:13:29,297 - INFO - Starting scheduler
2024-07-28 15:13:29,298 - INFO - Updater date and time: 2024-07-28 15:13:29.298725
2024-07-28 15:13:29,299 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-28 15:13:29,299 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-28 15:13:29,299 - INFO - Scheduler started
2024-07-28 15:13:29,300 - INFO - Current time of the scheduler: 2024-07-28 15:13:29.300725
2024-07-28 15:13:29,300 - INFO - Ending scheduler
2024-07-28 15:13:29,318 - INFO - Watching for file changes with StatReloader
2024-07-28 15:13:31,253 - WARNING - Not Found: /images/favicon.ico
2024-07-28 15:13:38,165 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-07-28 15:13:39,676 - WARNING - Not Found: /tickers/images/favicon.ico
2024-07-28 15:13:43,459 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-07-28 15:13:44,728 - WARNING - Not Found: /prices/update-price/a425290a-46a4-41b5-92a2-a2bb77cdbfe3/images/favicon.ico
2024-07-28 15:14:12,678 - ERROR - Internal Server Error: /prices/update-price/a425290a-46a4-41b5-92a2-a2bb77cdbfe3/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 58, in updatePrice
    run_model_predictions(price_instance.ticker.symbol)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 439, in run_model_predictions
    comparison_comment, send_email_enabled = compare_version_results(pred_collection, 0, 1 )
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\analysis_comments.py", line 249, in compare_version_results
    model_dict1 = pred_collection.pred_reverse_v4
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'pred_reverse_v4'
2024-07-28 15:14:12,794 - WARNING - Not Found: /favicon.ico
2024-07-28 15:17:12,577 - INFO - Starting scheduler
2024-07-28 15:17:12,578 - INFO - Updater date and time: 2024-07-28 15:17:12.578174
2024-07-28 15:17:12,579 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-28 15:17:12,579 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-28 15:17:12,579 - INFO - Scheduler started
2024-07-28 15:17:12,580 - INFO - Current time of the scheduler: 2024-07-28 15:17:12.580213
2024-07-28 15:17:12,580 - INFO - Ending scheduler
2024-07-28 15:17:14,966 - INFO - Starting scheduler
2024-07-28 15:17:14,967 - INFO - Updater date and time: 2024-07-28 15:17:14.967597
2024-07-28 15:17:14,968 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-28 15:17:14,968 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-28 15:17:14,968 - INFO - Scheduler started
2024-07-28 15:17:14,968 - INFO - Current time of the scheduler: 2024-07-28 15:17:14.968597
2024-07-28 15:17:14,968 - INFO - Ending scheduler
2024-07-28 15:17:14,990 - INFO - Watching for file changes with StatReloader
2024-07-28 15:33:22,562 - INFO - Starting scheduler
2024-07-28 15:33:22,563 - INFO - Updater date and time: 2024-07-28 15:33:22.563069
2024-07-28 15:33:22,564 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-28 15:33:22,564 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-28 15:33:22,564 - INFO - Scheduler started
2024-07-28 15:33:22,565 - INFO - Current time of the scheduler: 2024-07-28 15:33:22.565068
2024-07-28 15:33:22,565 - INFO - Ending scheduler
2024-07-28 15:33:24,921 - INFO - Starting scheduler
2024-07-28 15:33:24,922 - INFO - Updater date and time: 2024-07-28 15:33:24.921877
2024-07-28 15:33:24,922 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-28 15:33:24,923 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-28 15:33:24,923 - INFO - Scheduler started
2024-07-28 15:33:24,923 - INFO - Current time of the scheduler: 2024-07-28 15:33:24.923878
2024-07-28 15:33:24,923 - INFO - Ending scheduler
2024-07-28 15:33:24,948 - INFO - Watching for file changes with StatReloader
2024-07-28 15:39:09,219 - INFO - Starting scheduler
2024-07-28 15:39:09,220 - INFO - Updater date and time: 2024-07-28 15:39:09.220389
2024-07-28 15:39:09,221 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-28 15:39:09,221 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-28 15:39:09,221 - INFO - Scheduler started
2024-07-28 15:39:09,221 - INFO - Current time of the scheduler: 2024-07-28 15:39:09.221581
2024-07-28 15:39:09,221 - INFO - Ending scheduler
2024-07-28 15:39:11,502 - INFO - Starting scheduler
2024-07-28 15:39:11,503 - INFO - Updater date and time: 2024-07-28 15:39:11.502849
2024-07-28 15:39:11,503 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-07-28 15:39:11,504 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-07-28 15:39:11,504 - INFO - Scheduler started
2024-07-28 15:39:11,504 - INFO - Current time of the scheduler: 2024-07-28 15:39:11.504851
2024-07-28 15:39:11,504 - INFO - Ending scheduler
2024-07-28 15:39:11,526 - INFO - Watching for file changes with StatReloader
2024-07-28 15:39:23,983 - WARNING - Not Found: /tickers/update-ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-07-28 15:41:00,009 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-28 15:41:00 BST)" (scheduled at 2024-07-28 15:41:00+01:00)
2024-07-28 15:41:00,009 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-28 15:41:00 BST)" (scheduled at 2024-07-28 15:41:00+01:00)
2024-07-28 15:41:00,010 - INFO - Inside the procedure sequence
2024-07-28 15:41:00,010 - INFO - Inside the procedure sequence
2024-07-28 15:41:00,296 - INFO - The input start time: 2024-07-28 14:00:00
2024-07-28 15:41:00,297 - INFO - The input start time: 2024-07-28 14:00:00
2024-07-28 15:41:25,204 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-28 15:46:00 BST)" executed successfully
2024-07-28 15:41:26,600 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-07-28 15:46:00 BST)" executed successfully
