2024-09-29 16:38:22,806 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 16:38:22,807 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 16:38:22,807 - INFO - Scheduler started
2024-09-29 16:38:24,984 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 16:38:24,984 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 16:38:24,984 - INFO - Scheduler started
2024-09-29 16:38:25,006 - INFO - Watching for file changes with StatReloader
2024-09-29 16:38:27,453 - WARNING - Not Found: /images/favicon.ico
2024-09-29 16:38:35,231 - WARNING - Not Found: /login/images/favicon.ico
2024-09-29 16:39:14,602 - WARNING - Not Found: /account/images/favicon.ico
2024-09-29 16:40:18,367 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-09-29 16:40:21,501 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 16:40:21,502 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 16:40:21,502 - INFO - Scheduler started
2024-09-29 16:40:21,522 - INFO - Watching for file changes with StatReloader
2024-09-29 16:41:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 16:41:00 BST)" (scheduled at 2024-09-29 16:41:00+01:00)
2024-09-29 16:41:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 16:46:00 BST)" (scheduled at 2024-09-29 16:41:00+01:00)
2024-09-29 16:41:00,191 - INFO - The input start time: 2024-09-29 15:00:00
2024-09-29 16:41:00,191 - INFO - The input start time: 2024-09-29 15:00:00
2024-09-29 16:41:18,707 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 16:46:00 BST)" executed successfully
2024-09-29 16:41:20,200 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 16:46:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 74, in run_procedure_sequence
    comparison_comment, general_ticker_info, send_email_enabled = run_model_predictions(ticker)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 460, in run_model_predictions
    comparison_comment, send_email_enabled = compare_version_results(pred_collection, 1, 1 )
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\analysis_comments.py", line 262, in compare_version_results
    rev_array1 = model_rev1[rev_label1][2]['trade_results']['Potential Trade']
                 ~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 2
2024-09-29 16:41:21,011 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 16:42:36,374 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 16:42:36,375 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 16:42:36,375 - INFO - Scheduler started
2024-09-29 16:42:38,623 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 16:42:38,623 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 16:42:38,623 - INFO - Scheduler started
2024-09-29 16:42:38,642 - INFO - Watching for file changes with StatReloader
2024-09-29 16:42:42,099 - WARNING - Not Found: /tickers/images/favicon.ico
2024-09-29 16:42:45,757 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-09-29 16:42:46,473 - WARNING - Not Found: /prices/update-price/f3886890-7b8c-4e7e-b819-3b80b0245e2e/images/favicon.ico
2024-09-29 16:43:09,957 - ERROR - Internal Server Error: /prices/update-price/f3886890-7b8c-4e7e-b819-3b80b0245e2e/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 58, in updatePrice
    run_model_predictions(price_instance.ticker.symbol)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 460, in run_model_predictions
    comparison_comment, send_email_enabled = compare_version_results(pred_collection, 1, 1 )
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\analysis_comments.py", line 262, in compare_version_results
    rev_array1 = model_rev1[rev_label1][2]['trade_results']['Potential Trade']
                 ~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 2
2024-09-29 16:43:10,095 - WARNING - Not Found: /favicon.ico
2024-09-29 16:43:58,443 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-09-29 16:44:28,332 - ERROR - Internal Server Error: /prices/update-price/f3886890-7b8c-4e7e-b819-3b80b0245e2e/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 58, in updatePrice
    run_model_predictions(price_instance.ticker.symbol)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 460, in run_model_predictions
    comparison_comment, send_email_enabled = compare_version_results(pred_collection, 1, 1 )
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\analysis_comments.py", line 262, in compare_version_results
    rev_array1 = model_rev1[rev_label1][2]['trade_results']['Potential Trade']
                 ~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 2
2024-09-29 16:46:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 16:46:00 BST)" (scheduled at 2024-09-29 16:46:00+01:00)
2024-09-29 16:46:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 16:46:00 BST)" (scheduled at 2024-09-29 16:46:00+01:00)
2024-09-29 16:46:00,018 - INFO - The input start time: 2024-09-29 15:00:00
2024-09-29 16:46:00,162 - INFO - The input start time: 2024-09-29 15:00:00
2024-09-29 16:46:00,787 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 16:51:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 166, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-09-29 16:46:06,384 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\analysis_comments.py changed, reloading.
2024-09-29 16:46:17,531 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 16:51:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 74, in run_procedure_sequence
    comparison_comment, general_ticker_info, send_email_enabled = run_model_predictions(ticker)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 460, in run_model_predictions
    comparison_comment, send_email_enabled = compare_version_results(pred_collection, 1, 1 )
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\analysis_comments.py", line 262, in compare_version_results
    rev_array1 = model_rev1[rev_label1]['trade_results']['Potential Trade']
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 2
2024-09-29 16:46:20,913 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 16:46:20,913 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 16:46:20,913 - INFO - Scheduler started
2024-09-29 16:46:20,935 - INFO - Watching for file changes with StatReloader
2024-09-29 16:46:24,145 - WARNING - Not Found: /prices/
2024-09-29 19:49:09,529 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 19:49:09,529 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 19:49:09,529 - INFO - Scheduler started
2024-09-29 19:49:11,814 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 19:49:11,814 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 19:49:11,814 - INFO - Scheduler started
2024-09-29 19:49:11,836 - INFO - Watching for file changes with StatReloader
2024-09-29 19:50:03,979 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 19:50:07,134 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 19:50:07,134 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 19:50:07,134 - INFO - Scheduler started
2024-09-29 19:50:07,156 - INFO - Watching for file changes with StatReloader
2024-09-29 19:51:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 19:51:00 BST)" (scheduled at 2024-09-29 19:51:00+01:00)
2024-09-29 19:51:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 19:56:00 BST)" (scheduled at 2024-09-29 19:51:00+01:00)
2024-09-29 19:51:00,016 - INFO - The input start time: 2024-09-29 18:00:00
2024-09-29 19:51:00,166 - INFO - The input start time: 2024-09-29 18:00:00
2024-09-29 19:51:29,641 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 19:56:00 BST)" executed successfully
2024-09-29 19:51:46,894 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 19:56:00 BST)" executed successfully
2024-09-29 19:56:00,008 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:01:00 BST)" (scheduled at 2024-09-29 19:56:00+01:00)
2024-09-29 19:56:00,011 - INFO - The input start time: 2024-09-29 18:00:00
2024-09-29 19:56:00,011 - INFO - The input start time: 2024-09-29 18:00:00
2024-09-29 19:56:18,852 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:01:00 BST)" executed successfully
2024-09-29 19:56:19,708 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:01:00 BST)" executed successfully
2024-09-29 19:56:56,868 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-09-29 19:58:20,115 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 19:58:20,115 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 19:58:20,115 - INFO - Scheduler started
2024-09-29 19:58:22,610 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 19:58:22,610 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 19:58:22,610 - INFO - Scheduler started
2024-09-29 19:58:22,627 - INFO - Watching for file changes with StatReloader
2024-09-29 19:59:27,822 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 19:59:31,006 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 19:59:31,007 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 19:59:31,007 - INFO - Scheduler started
2024-09-29 19:59:31,028 - INFO - Watching for file changes with StatReloader
2024-09-29 20:00:38,564 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 20:00:41,736 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:00:41,736 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:00:41,736 - INFO - Scheduler started
2024-09-29 20:00:41,753 - INFO - Watching for file changes with StatReloader
2024-09-29 20:00:48,618 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 448, in ml_report2
    if key_results.potential_trade.hist == 'Buy':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'potential_trade'
2024-09-29 20:01:00,013 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:01:00 BST)" (scheduled at 2024-09-29 20:01:00+01:00)
2024-09-29 20:01:00,013 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:01:00 BST)" (scheduled at 2024-09-29 20:01:00+01:00)
2024-09-29 20:01:00,017 - INFO - The input start time: 2024-09-29 19:00:00
2024-09-29 20:01:00,169 - INFO - The input start time: 2024-09-29 19:00:00
2024-09-29 20:01:22,856 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:06:00 BST)" executed successfully
2024-09-29 20:01:23,648 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:06:00 BST)" executed successfully
2024-09-29 20:01:57,619 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 20:02:09,120 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:02:09,120 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:02:09,120 - INFO - Scheduler started
2024-09-29 20:02:11,392 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:02:11,392 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:02:11,393 - INFO - Scheduler started
2024-09-29 20:02:11,412 - INFO - Watching for file changes with StatReloader
2024-09-29 20:02:16,330 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 485, in ml_report2
    exit_point = open_prices[-1] + trade_target/100/exit_adjustment + entry_adjustment
                                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'trade_target' where it is not associated with a value
2024-09-29 20:04:11,293 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 485, in ml_report2
    exit_point = open_prices[-1] + trade_target/100/exit_adjustment + entry_adjustment
                                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'trade_target' where it is not associated with a value
2024-09-29 20:05:27,195 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 20:05:30,057 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:05:30,057 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:05:30,058 - INFO - Scheduler started
2024-09-29 20:05:30,079 - INFO - Watching for file changes with StatReloader
2024-09-29 20:05:31,905 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 512, in ml_report2
    if potential_trade == "Buy":
       ^^^^^^^^^^^^^^^
NameError: name 'potential_trade' is not defined
2024-09-29 20:06:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:06:00 BST)" (scheduled at 2024-09-29 20:06:00+01:00)
2024-09-29 20:06:00,016 - INFO - The input start time: 2024-09-29 19:00:00
2024-09-29 20:06:00,154 - INFO - The input start time: 2024-09-29 19:00:00
2024-09-29 20:06:00,690 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 166, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-09-29 20:06:06,073 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 20:06:13,748 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 512, in ml_report2
    if potential_trade == "Buy":
       ^^^^^^^^^^^^^^^
NameError: name 'potential_trade' is not defined
2024-09-29 20:06:18,611 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:11:00 BST)" executed successfully
2024-09-29 20:06:21,652 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:06:21,652 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:06:21,652 - INFO - Scheduler started
2024-09-29 20:06:21,671 - INFO - Watching for file changes with StatReloader
2024-09-29 20:06:28,953 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 512, in ml_report2
    if potential_trade == "Buy":
       ^^^^^^^^^^^^^^^
NameError: name 'potential_trade' is not defined
2024-09-29 20:07:14,442 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 20:07:17,576 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:07:17,577 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:07:17,577 - INFO - Scheduler started
2024-09-29 20:07:17,598 - INFO - Watching for file changes with StatReloader
2024-09-29 20:08:36,962 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-09-29 20:08:40,207 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:08:40,207 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:08:40,207 - INFO - Scheduler started
2024-09-29 20:08:40,227 - INFO - Watching for file changes with StatReloader
2024-09-29 20:09:01,780 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-09-29 20:09:04,910 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:09:04,910 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:09:04,910 - INFO - Scheduler started
2024-09-29 20:09:04,931 - INFO - Watching for file changes with StatReloader
2024-09-29 20:11:00,004 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:16:00 BST)" (scheduled at 2024-09-29 20:11:00+01:00)
2024-09-29 20:11:00,004 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:16:00 BST)" (scheduled at 2024-09-29 20:11:00+01:00)
2024-09-29 20:11:00,008 - INFO - The input start time: 2024-09-29 19:00:00
2024-09-29 20:11:00,011 - INFO - The input start time: 2024-09-29 19:00:00
2024-09-29 20:11:21,727 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:16:00 BST)" executed successfully
2024-09-29 20:11:22,259 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:16:00 BST)" executed successfully
2024-09-29 20:38:57,673 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:38:57,673 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:38:57,673 - INFO - Scheduler started
2024-09-29 20:38:59,832 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:38:59,832 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:38:59,832 - INFO - Scheduler started
2024-09-29 20:38:59,851 - INFO - Watching for file changes with StatReloader
2024-09-29 20:39:13,704 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 531, in ml_report2
    'flatness1':flatness1,
                ^^^^^^^^^
NameError: name 'flatness1' is not defined
2024-09-29 20:39:31,595 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 20:39:34,677 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:39:34,677 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:39:34,677 - INFO - Scheduler started
2024-09-29 20:39:34,697 - INFO - Watching for file changes with StatReloader
2024-09-29 20:41:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:41:00 BST)" (scheduled at 2024-09-29 20:41:00+01:00)
2024-09-29 20:41:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:46:00 BST)" (scheduled at 2024-09-29 20:41:00+01:00)
2024-09-29 20:41:00,030 - INFO - The input start time: 2024-09-29 19:00:00
2024-09-29 20:41:00,175 - INFO - The input start time: 2024-09-29 19:00:00
2024-09-29 20:41:19,290 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:46:00 BST)" executed successfully
2024-09-29 20:41:20,065 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-09-29 20:46:00 BST)" executed successfully
2024-09-29 20:42:58,483 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 20:43:05,620 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:43:05,621 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:43:05,621 - INFO - Scheduler started
2024-09-29 20:43:08,087 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:43:08,087 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:43:08,087 - INFO - Scheduler started
2024-09-29 20:43:08,108 - INFO - Watching for file changes with StatReloader
2024-09-29 20:43:49,022 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 20:43:51,971 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:43:51,971 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:43:51,971 - INFO - Scheduler started
2024-09-29 20:43:51,995 - INFO - Watching for file changes with StatReloader
2024-09-29 20:44:17,866 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-09-29 20:44:21,052 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-29 20:44:21,052 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-29 20:44:21,052 - INFO - Scheduler started
2024-09-29 20:44:21,074 - INFO - Watching for file changes with StatReloader
2024-09-30 19:09:16,219 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-30 19:09:16,220 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-30 19:09:16,220 - INFO - Scheduler started
2024-09-30 19:09:19,374 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-09-30 19:09:19,374 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-09-30 19:09:19,374 - INFO - Scheduler started
2024-09-30 19:09:19,405 - INFO - Watching for file changes with StatReloader
2024-09-30 19:09:24,942 - WARNING - Not Found: /images/favicon.ico
2024-09-30 19:09:36,378 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-09-30 19:09:37,278 - WARNING - Not Found: /tickers/images/favicon.ico
2024-10-06 21:54:45,164 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-06 21:54:45,165 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-06 21:54:45,165 - INFO - Scheduler started
2024-10-06 21:54:47,523 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-06 21:54:47,523 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-06 21:54:47,523 - INFO - Scheduler started
2024-10-06 21:54:47,542 - INFO - Watching for file changes with StatReloader
2024-10-06 21:54:49,770 - WARNING - Not Found: /images/favicon.ico
2024-10-06 21:54:59,581 - WARNING - Not Found: /tickers/images/favicon.ico
2024-10-06 21:55:03,029 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-10-06 21:55:03,839 - WARNING - Not Found: /prices/update-price/f3886890-7b8c-4e7e-b819-3b80b0245e2e/images/favicon.ico
2024-10-06 21:55:32,576 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-10-06 21:56:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-06 21:56:00 BST)" (scheduled at 2024-10-06 21:56:00+01:00)
2024-10-06 21:56:00,004 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-06 21:56:00 BST)" (scheduled at 2024-10-06 21:56:00+01:00)
2024-10-06 21:56:00,019 - INFO - The input start time: 2024-10-06 20:00:00
2024-10-06 21:56:00,166 - INFO - The input start time: 2024-10-06 20:00:00
2024-10-06 21:56:00,734 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-06 22:01:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 166, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-10-06 21:56:18,195 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-06 22:01:00 BST)" executed successfully
2024-10-06 22:14:33,485 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-06 22:14:33,486 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-06 22:14:33,486 - INFO - Scheduler started
2024-10-06 22:14:35,854 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-06 22:14:35,854 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-06 22:14:35,855 - INFO - Scheduler started
2024-10-06 22:14:35,880 - INFO - Watching for file changes with StatReloader
2024-10-06 22:15:03,837 - ERROR - Internal Server Error: /prices/update-price/f3886890-7b8c-4e7e-b819-3b80b0245e2e/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 58, in updatePrice
    run_model_predictions(price_instance.ticker.symbol)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 464, in run_model_predictions
    trade_target = hist_trade_target
                   ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'hist_trade_target' where it is not associated with a value
2024-10-06 22:15:03,942 - WARNING - Not Found: /favicon.ico
2024-10-06 22:16:00,004 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-06 22:16:00 BST)" (scheduled at 2024-10-06 22:16:00+01:00)
2024-10-06 22:16:00,004 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-06 22:16:00 BST)" (scheduled at 2024-10-06 22:16:00+01:00)
2024-10-06 22:16:00,168 - INFO - The input start time: 2024-10-06 21:00:00
2024-10-06 22:16:00,168 - INFO - The input start time: 2024-10-06 21:00:00
2024-10-06 22:16:23,738 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-06 22:21:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 74, in run_procedure_sequence
    comparison_comment, general_ticker_info, send_email_enabled = run_model_predictions(ticker)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 464, in run_model_predictions
    trade_target = hist_trade_target
                   ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'hist_trade_target' where it is not associated with a value
2024-10-06 22:16:24,393 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-06 22:21:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 74, in run_procedure_sequence
    comparison_comment, general_ticker_info, send_email_enabled = run_model_predictions(ticker)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 464, in run_model_predictions
    trade_target = hist_trade_target
                   ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'hist_trade_target' where it is not associated with a value
2024-10-08 20:24:56,458 - INFO - Watching for file changes with StatReloader
2024-10-08 20:25:37,251 - INFO - Watching for file changes with StatReloader
2024-10-08 20:26:53,541 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 20:26:53,541 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 20:26:53,541 - INFO - Scheduler started
2024-10-08 20:26:56,112 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 20:26:56,112 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 20:26:56,112 - INFO - Scheduler started
2024-10-08 20:26:56,138 - INFO - Watching for file changes with StatReloader
2024-10-08 20:26:58,497 - WARNING - Not Found: /images/favicon.ico
2024-10-08 20:27:00,282 - WARNING - Not Found: /tickers/images/favicon.ico
2024-10-08 20:27:04,757 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-10-08 20:27:06,667 - WARNING - Not Found: /prices/update-price/a9bdc8f9-8583-4b8b-805b-b4c94fe549e9/images/favicon.ico
2024-10-08 20:27:37,137 - ERROR - Internal Server Error: /prices/update-price/a9bdc8f9-8583-4b8b-805b-b4c94fe549e9/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 58, in updatePrice
    run_model_predictions(price_instance.ticker.symbol)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 489, in run_model_predictions
    trade_target = hist_trade_target
                   ^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'hist_trade_target' where it is not associated with a value
2024-10-08 20:27:37,419 - WARNING - Not Found: /favicon.ico
2024-10-08 20:30:51,072 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 20:30:51,072 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 20:30:51,072 - INFO - Scheduler started
2024-10-08 20:30:53,463 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 20:30:53,463 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 20:30:53,463 - INFO - Scheduler started
2024-10-08 20:30:53,484 - INFO - Watching for file changes with StatReloader
2024-10-08 20:31:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 20:31:00 BST)" (scheduled at 2024-10-08 20:31:00+01:00)
2024-10-08 20:31:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 20:36:00 BST)" (scheduled at 2024-10-08 20:31:00+01:00)
2024-10-08 20:31:00,304 - INFO - The input start time: 2024-10-08 19:00:00
2024-10-08 20:31:00,304 - INFO - The input start time: 2024-10-08 19:00:00
2024-10-08 20:31:01,096 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 20:36:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 166, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-10-08 20:31:57,445 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 20:36:00 BST)" executed successfully
2024-10-08 20:35:32,735 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 20:35:32,736 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 20:35:32,736 - INFO - Scheduler started
2024-10-08 20:35:34,961 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 20:35:34,961 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 20:35:34,961 - INFO - Scheduler started
2024-10-08 20:35:34,980 - INFO - Watching for file changes with StatReloader
2024-10-08 20:35:46,228 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-10-08 20:36:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 20:36:00 BST)" (scheduled at 2024-10-08 20:36:00+01:00)
2024-10-08 20:36:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 20:36:00 BST)" (scheduled at 2024-10-08 20:36:00+01:00)
2024-10-08 20:36:00,015 - INFO - The input start time: 2024-10-08 19:00:00
2024-10-08 20:36:00,216 - INFO - The input start time: 2024-10-08 19:00:00
2024-10-08 20:36:00,701 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 20:41:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 166, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-10-08 20:36:19,688 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 20:41:00 BST)" executed successfully
2024-10-08 20:59:43,084 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 20:59:43,084 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 20:59:43,084 - INFO - Scheduler started
2024-10-08 20:59:45,491 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 20:59:45,492 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 20:59:45,492 - INFO - Scheduler started
2024-10-08 20:59:45,512 - INFO - Watching for file changes with StatReloader
2024-10-08 20:59:48,888 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-10-08 20:59:52,071 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 20:59:52,071 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 20:59:52,071 - INFO - Scheduler started
2024-10-08 20:59:52,092 - INFO - Watching for file changes with StatReloader
2024-10-08 21:00:59,554 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-10-08 21:01:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:01:00 BST)" (scheduled at 2024-10-08 21:01:00+01:00)
2024-10-08 21:01:00,006 - ERROR - Error submitting job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:01:00 BST)" to executor "default"
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\schedulers\base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\concurrent\futures\thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
2024-10-08 21:01:00,169 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:01:03,022 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:01:03,022 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:01:03,022 - INFO - Scheduler started
2024-10-08 21:01:03,049 - INFO - Watching for file changes with StatReloader
2024-10-08 21:01:18,218 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:06:00 BST)" executed successfully
2024-10-08 21:04:52,383 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-10-08 21:06:08,207 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:06:08,207 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:06:08,207 - INFO - Scheduler started
2024-10-08 21:06:10,455 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:06:10,455 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:06:10,455 - INFO - Scheduler started
2024-10-08 21:06:10,478 - INFO - Watching for file changes with StatReloader
2024-10-08 21:09:14,615 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-10-08 21:09:17,644 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:09:17,644 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:09:17,644 - INFO - Scheduler started
2024-10-08 21:09:17,662 - INFO - Watching for file changes with StatReloader
2024-10-08 21:11:00,006 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:11:00 BST)" (scheduled at 2024-10-08 21:11:00+01:00)
2024-10-08 21:11:00,006 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:16:00 BST)" (scheduled at 2024-10-08 21:11:00+01:00)
2024-10-08 21:11:00,173 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:11:00,174 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:11:18,402 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:16:00 BST)" executed successfully
2024-10-08 21:11:19,983 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:16:00 BST)" executed successfully
2024-10-08 21:13:47,244 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-10-08 21:13:55,185 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:13:55,185 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:13:55,185 - INFO - Scheduler started
2024-10-08 21:13:57,374 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:13:57,375 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:13:57,375 - INFO - Scheduler started
2024-10-08 21:13:57,399 - INFO - Watching for file changes with StatReloader
2024-10-08 21:15:52,934 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-10-08 21:15:56,915 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:15:56,916 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:15:56,916 - INFO - Scheduler started
2024-10-08 21:15:56,951 - INFO - Watching for file changes with StatReloader
2024-10-08 21:16:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:16:00 BST)" (scheduled at 2024-10-08 21:16:00+01:00)
2024-10-08 21:16:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:16:00 BST)" (scheduled at 2024-10-08 21:16:00+01:00)
2024-10-08 21:16:00,016 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:16:00,350 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:16:00,970 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:21:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 166, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-10-08 21:16:21,587 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:21:00 BST)" executed successfully
2024-10-08 21:18:54,282 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-10-08 21:19:23,582 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:19:23,583 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:19:23,583 - INFO - Scheduler started
2024-10-08 21:19:25,898 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:19:25,898 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:19:25,898 - INFO - Scheduler started
2024-10-08 21:19:25,921 - INFO - Watching for file changes with StatReloader
2024-10-08 21:19:48,062 - WARNING - Not Found: /prices/update-price/ae7d4b5a-827b-4e0a-ad86-57adc03e60da/images/favicon.ico
2024-10-08 21:20:36,605 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-10-08 21:20:39,752 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:20:39,752 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:20:39,752 - INFO - Scheduler started
2024-10-08 21:20:39,769 - INFO - Watching for file changes with StatReloader
2024-10-08 21:21:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:21:00 BST)" (scheduled at 2024-10-08 21:21:00+01:00)
2024-10-08 21:21:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:26:00 BST)" (scheduled at 2024-10-08 21:21:00+01:00)
2024-10-08 21:21:00,199 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:21:00,204 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:21:18,868 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:26:00 BST)" executed successfully
2024-10-08 21:21:20,384 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:26:00 BST)" executed successfully
2024-10-08 21:21:20,824 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py changed, reloading.
2024-10-08 21:23:07,850 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:23:07,850 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:23:07,850 - INFO - Scheduler started
2024-10-08 21:23:10,062 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:23:10,062 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:23:10,062 - INFO - Scheduler started
2024-10-08 21:23:10,080 - INFO - Watching for file changes with StatReloader
2024-10-08 21:26:00,001 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:31:00 BST)" (scheduled at 2024-10-08 21:26:00+01:00)
2024-10-08 21:26:00,002 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:26:00 BST)" (scheduled at 2024-10-08 21:26:00+01:00)
2024-10-08 21:26:00,007 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:26:00,161 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:26:19,612 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:31:00 BST)" executed successfully
2024-10-08 21:26:20,492 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:31:00 BST)" executed successfully
2024-10-08 21:27:24,817 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-10-08 21:27:37,820 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:27:37,820 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:27:37,820 - INFO - Scheduler started
2024-10-08 21:27:40,165 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:27:40,165 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:27:40,165 - INFO - Scheduler started
2024-10-08 21:27:40,185 - INFO - Watching for file changes with StatReloader
2024-10-08 21:30:27,897 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:30:27,897 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:30:27,897 - INFO - Scheduler started
2024-10-08 21:30:30,065 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-10-08 21:30:30,065 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-10-08 21:30:30,065 - INFO - Scheduler started
2024-10-08 21:30:30,087 - INFO - Watching for file changes with StatReloader
2024-10-08 21:31:00,008 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:31:00 BST)" (scheduled at 2024-10-08 21:31:00+01:00)
2024-10-08 21:31:00,008 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:36:00 BST)" (scheduled at 2024-10-08 21:31:00+01:00)
2024-10-08 21:31:00,014 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:31:00,214 - INFO - The input start time: 2024-10-08 20:00:00
2024-10-08 21:31:31,888 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:36:00 BST)" executed successfully
2024-10-08 21:31:32,754 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-10-08 21:36:00 BST)" executed successfully
